### ISSUE TITLE
Cannot connect Metamask or Celo Browser Extension wallet

### ISSUE THREAD

**Issue by critesjosh** [celo-tools/use-contractkit#1]
Trying to get this working with the [web dapp tutorial](https://docs.celo.org/developer-guide/start/web-dapp). I added the `next.config.js` file specified [here](https://github.com/celo-org/celo-monorepo/blob/e2be93067e6f9540f2151bf329a973ca08ed320e/packages/docs/developer-resources/walkthroughs/web-dapp.md).

I am unable to connect Metamask or the [Celo browser extension](https://chrome.google.com/webstore/detail/celoextensionwallet/kkilomkmpmkbdnfelcpgckmpcaemjcdh) wallet. I see the following errors.

```
react.development.js?72d0:220 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Modal`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at Modal (webpack-internal:///./node_modules/@celo-tools/use-contractkit/lib/modal.js:117:23)
    at Provider (webpack-internal:///./node_modules/unstated-next/dist/unstated-next.mjs:11:31)
    at ContractKitProvider (webpack-internal:///./node_modules/@celo-tools/use-contractkit/lib/use-contractkit.js:164:23)
    at div
    at WrappedApp
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:152:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:641:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:772:24)
```

```
Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at WarningComponent.render (warning.js:1)
    at p._renderValidatedComponentWithoutOwnerOrContext (react-dom.min.js:13)
    at p._renderValidatedComponent (react-dom.min.js:13)
    at performInitialMount (react-dom.min.js:13)
    at p.mountComponent (react-dom.min.js:13)
    at Object.mountComponent (react-dom.min.js:14)
    at performInitialMount (react-dom.min.js:13)
    at p.mountComponent (react-dom.min.js:13)
```

```
warning.js?d96e:34 Warning: react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen readers don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.
```

<img width="1792" alt="Screen Shot 2021-03-15 at 1 20 55 PM" src="https://user-images.githubusercontent.com/18372439/111194186-4dfb5080-8591-11eb-9fab-1549d59d7f21.png">

**Comment by AlexBHarley** [comment]
Most of those are warnings (will take the time to sort them out however), but with the latest @celo-tools/use-contractkit release (0.0.28) I verified it was working with the Celo Extension Wallet.
